jobs: 
- job: 
  displayName: Microsoft.Azure.Cosmos.Tests
  pool:
    vmImage: 'windows-2019' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
    
  steps:
  - script: dotnet --version
    displayName: dotnet version
    
  - task: DotNetCoreCLI@2
    displayName: Test Microsoft.Azure.Cosmos.Tests
    inputs:
      command: test 
      projects: 'Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --filter "TestCategory!=Quarantine" --logger trx --results-directory $(Agent.TempDirectory)'

- job: 
  displayName: Microsoft.Azure.NetFramework.Tests
  pool:
    vmImage: 'windows-2019' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops

  steps:
  - template:  templates/emulator-setup.yml

  - task: DotNetCoreCLI@2
    displayName: Test Microsoft.Azure.Cosmos.NetFramework.Tests
    inputs:
      command: test 
      projects: 'Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.NetFramework.Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --filter "TestCategory!=Quarantine" --logger trx --results-directory $(Agent.TempDirectory)'

