jobs: 
- job: 
  displayName: Microsoft.Azure.Cosmos.Tests
  pool:
    vmImage: '$(Image)' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
    
  steps:
  - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
    clean: true  # if true, execute `execute git clean -ffdx && git reset --hard HEAD` before fetching
    lfs: true  # whether to download Git-LFS files; defaults to false

  - task: DotNetCoreCLI@2
    displayName: Test Microsoft.Azure.Cosmos.Tests
    inputs:
      command: test 
      projects: 'Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/*.csproj'
      arguments: ' --filter "TestCategory!=Quarantine" --collect:"Code Coverage"'
      configuration: '$(BuildConfiguration)'
      publishTestResults: true 

#- job: 
#  displayName: Microsoft.Azure.NetFramework.Tests
#  pool:
#    vmImage: '$(Image)' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
#
#  steps:
#  - template:  templates/emulator-setup.yml
#
#  - task: DotNetCoreCLI@2
#    displayName: Test Microsoft.Azure.Cosmos.NetFramework.Tests
#    condition: succeeded() 
#    inputs:
#      command: test 
#      projects: 'Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.NetFramework.Tests/*.csproj'
#      arguments: ' --filter "TestCategory!=Quarantine" '
#      configuration: '$(BuildConfiguration)'
#      publishTestResults: true 
#
#
#- job: 
#  displayName: Microsoft.Azure.Cosmos.EmulatorTests
#  pool:
#    vmImage: '$(Image)' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
#
#  steps:
#  - template:  templates/emulator-setup.yml
#
#  - task: DotNetCoreCLI@2
#    displayName: Test Microsoft.Azure.Cosmos.EmulatorTests
#    condition: succeeded() 
#    inputs:
#      command: test 
#      projects: 'Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/*.csproj'
#      arguments: ' --filter "TestCategory!=Quarantine" '
#      configuration: '$(BuildConfiguration)'
#      publishTestResults: true 

