trigger: none

pr: none

variables:
  ReleaseArguments: ' --filter "TestCategory!=Quarantine" --verbosity normal ' 
  VmImage: windows-latest # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops 
  BuildConfiguration: Release 

stages:
- stage:
  displayName: Gate 
  jobs:
    - template:  templates/static-tools.yml
      parameters:
        BuildConfiguration: $(BuildConfiguration)
        VmImage: $(VmImage)

    - template:  templates/build-test.yml
      parameters:
        BuildConfiguration: $(BuildConfiguration)
        Arguments: $(ReleaseArguments)
        VmImage: $(VmImage)

- stage:
  displayName: Publish 
  jobs:
    - job:
      pool:
        vmImage: $(VmImage)
    
      steps:
      - task: DotNetCoreCLI@2
        displayName: Build Microsoft.Azure.Cosmos
        inputs: 
          command: build  
          configuration: $(BuildConfiguration)
          nugetConfigPath: NuGet.config
          projects: Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj 
          arguments: --configuration $(BuildConfiguration) /p:Optimize=true 
          versioningScheme: OFF

      - task: DotNetCoreCLI@2
        displayName: Pack Microsoft.Azure.Cosmos
        inputs: 
          command: pack 
          configuration: $(BuildConfiguration)
          searchPatternPack: Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
          arguments: -v detailed -c $(BuildConfiguration) --no-build --no-restore -o "$(Build.ArtifactStagingDirectory)\bin\AnyCPU\$(BuildConfiguration)\Microsoft.Azure.Cosmos"
          versioningScheme: OFF

      - task: DotNetCoreCLI@2
        displayName: Pack Microsoft.Azure.Cosmos Symbols
        inputs: 
          command: pack 
          configuration: $(BuildConfiguration)
          searchPatternPack: Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
          arguments: -v detailed -c $(BuildConfiguration) --no-build --include-symbols /p:SymbolPackageFormat=snupkg --no-restore -o "$(Build.ArtifactStagingDirectory)\bin\AnyCPU\$(BuildConfiguration)\Microsoft.Azure.Cosmos"
          versioningScheme: OFF

      - task: AzureFileCopy@2
        displayName: ' Copy Artifacts to Azure SDK Release blob storage'
        inputs:
        SourcePath: '$(Build.ArtifactStagingDirectory)/bin/AnyCPU/$(BuildConfiguration)/Microsoft.Azure.Cosmos'
        azureSubscription: azuresdkpartnerdrops
        Destination: AzureBlob
        storage: azuresdkpartnerdrops
        ContainerName: 'https://azuresdkpartnerdrops.blob.core.windows.net/drops'
        BlobPrefix: 'cosmosdb/cshar/$(Version)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts: Microsoft.Azure.Cosmos'
        inputs:
          artifactName: Microsoft.Azure.Cosmos
#