jobs: 
- job: 
  displayName: Microsoft.Azure.Cosmos.Tests
  pool:
    vmImage: 'windows-2019' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
    
  steps:
  - task: DotNetCoreCLI@2
    displayName: Test Microsoft.Azure.Cosmos.Tests
    inputs:
      command: test 
      projects: 'Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --filter "FullyQualifiedName=Microsoft.Azure.Cosmos.ContractTests"'

- job: 
  displayName: Microsoft.Azure.NetFramework.Tests
  pool:
    vmImage: 'windows-2019' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  steps:
  - pwsh:  |
        Write-Host "Downloading Cosmos Emulator - $env:EMULATORMSIURL" -ForegroundColor green 
        Invoke-WebRequest "$env:EMULATORMSIURL" -OutFile "$env:temp\azure-cosmosdb-emulator.msi"
        Write-Host "Finished Downloading Cosmos Emulator - $env:temp\azure-cosmosdb-emulator.msi" -ForegroundColor green 
        dir "$env:temp" 
        choco install lessmsi
        choco upgrade lessmsi
        mkdir "$env:temp\Azure Cosmos DB Emulator"
        lessmsi x "$env:temp\azure-cosmosdb-emulator.msi" "$env:temp\Azure Cosmos DB Emulator\"
        Write-Host "Starting Comsos DB Emulator" -ForegroundColor green 
        Start-Process "$env:temp\Azure Cosmos DB Emulator\SourceDir\Azure Cosmos DB Emulator\CosmosDB.Emulator.exe" "/NoExplorer /NoUI /DisableRateLimiting /PartitionCount=100 /Consistency=Strong /enableRio" -Verb RunAs
        Import-Module "$env:temp\Azure Cosmos DB Emulator\SourceDir\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
        Get-Item env:* | Sort-Object -Property Name
        for ($i=0; $i -lt 8; $i++) {
          $status=Get-CosmosDbEmulatorStatus 
          if ($status -ne "Running") {
            sleep 30;
            Write-Host "Cosmos DB Emulator Status: $status" -ForegroundColor yellow
          } else {
            break;
          }
        }
      
    displayName:  Install Public Cosmos DB Emulator
    failOnStderr:  true
    errorActionPreference:  stop

  - task: DotNetCoreCLI@2
    displayName: Test Microsoft.Azure.Cosmos.NetFramework.Tests
    inputs:
      command: test 
      projects: 'Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.NetFramework.Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

