trigger: none

pr: none

variables:
  ReleaseArguments: ' --filter "TestCategory!=Quarantine" --verbosity normal ' 
  VmImage: windows-latest # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops 
  BuildConfiguration: Release 

stages:
- stage:
  displayName: Gate 
  jobs:
    - template:  templates/static-tools.yml
      parameters:
        BuildConfiguration: $(BuildConfiguration)
        VmImage: $(VmImage)

    - template:  templates/build-test.yml
      parameters:
        BuildConfiguration: $(BuildConfiguration)
        Arguments: $(ReleaseArguments)
        VmImage: $(VmImage)

- stage:
  displayName: Publish 
  jobs:
    - job:
      pool:
        vmImage: $(VmImage)
    
      steps:
      - task: DotNetCoreCLI@2
        displayName: Build Microsoft.Azure.Cosmos
        inputs: 
          command: build  
          configuration: $(BuildConfiguration)
          nugetConfigPath: NuGet.config
          projects: Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj 
          arguments: --configuration $(BuildConfiguration) /p:Optimize=true 
          versioningScheme: OFF

      - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
        displayName: 'ESRP CodeSigning - binaries'
        inputs:
        ConnectedServiceName: 'ESRP Code Signing 2019'
        FolderPath: Microsoft.Azure.Cosmos
        Pattern: Microsoft.Azure.Cosmos.Client.dll
        signConfigType: inlineSignParams
        inlineOperation: |
            [
                {
                    "keyCode": "CP-233863-SN",
                    "operationSetCode": "StrongNameSign",
                    "parameters": [],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                },    {
                    "keyCode": "CP-230012",
                    "operationSetCode": "SigntoolSign",
                    "parameters": [
                    {
                        "parameterName": "OpusName",
                        "parameterValue": "Microsoft"
                    },
                    {
                        "parameterName": "OpusInfo",
                        "parameterValue": "http://www.microsoft.com"
                    },
                    {
                        "parameterName": "FileDigest",
                        "parameterValue": "/fd \"SHA256\""
                    },
                    {
                        "parameterName": "PageHash",
                        "parameterValue": "/NPH"
                    },
                    {
                        "parameterName": "TimeStamp",
                        "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                    }
                    ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                }, {
                    "keyCode": "CP-233863-SN",
                    "operationSetCode": "StrongNameVerify",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                }, {
                    "keyCode": "CP-230012",
                    "operationSetCode": "SigntoolVerify",
                    "parameters": [{
                        "parameterName": "VerifyAll",
                        "parameterValue": "/all"
                    }],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                }
            ]
        SessionTimeout: 20

      - task: DotNetCoreCLI@2
        displayName: Pack Microsoft.Azure.Cosmos
        inputs: 
          command: pack 
          configuration: $(BuildConfiguration)
          searchPatternPack: Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
          arguments: -v detailed -c $(BuildConfiguration) --no-build --no-restore -o "$(Build.ArtifactStagingDirectory)\bin\AnyCPU\$(BuildConfiguration)\Microsoft.Azure.Cosmos"
          versioningScheme: OFF

      - task: DotNetCoreCLI@2
        displayName: Pack Microsoft.Azure.Cosmos Symbols
        inputs: 
          command: pack 
          configuration: $(BuildConfiguration)
          searchPatternPack: Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
          arguments: -v detailed -c $(BuildConfiguration) --no-build --include-symbols /p:SymbolPackageFormat=snupkg --no-restore -o "$(Build.ArtifactStagingDirectory)\bin\AnyCPU\$(BuildConfiguration)\Microsoft.Azure.Cosmos"
          versioningScheme: OFF

       - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
         displayName: 'ESRP CodeSigning - nuget'
         inputs:
         ConnectedServiceName: 'ESRP Code Signing 2019'
         FolderPath: $(Build.ArtifactStagingDirectory)\bin
         Pattern: 'Microsoft.Azure.Cosmos*.nupkg'
         signConfigType: inlineSignParams
         inlineOperation: |
             [ 
                 {
                     "keyCode": "CP-401405",
                     "operationSetCode": "NuGetSign",
                     "parameters": [ ],
                     "toolName": "sign",
                     "toolVersion": "1.0"
                 },
                 {
                     "keyCode": "CP-401405",
                     "operationSetCode": "NuGetVerify",
                     "parameters": [ ],
                     "toolName": "sign",
                     "toolVersion": "1.0"
                 }
             ]
          SessionTimeout: 20

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts: Microsoft.Azure.Cosmos'
        inputs:
          artifactName: Microsoft.Azure.Cosmos
