jobs: 
- job: 
  displayName: Microsoft.Azure.Cosmos.Tests
  pool:
    vmImage: 'windows-2019' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
    
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 2.1.503
      
  - task: DotNetCoreCLI@2
    displayName: Test Microsoft.Azure.Cosmos.Tests
    inputs:
      command: test 
      projects: 'Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/*.csproj'
      arguments: ' --filter "TestCategory!=Quarantine" --collect:"Code Coverage"'
      configuration: '$(BuildConfiguration)'
      publishTestResults: true 

#- job: 
#  displayName: Microsoft.Azure.NetFramework.Tests
#  pool:
#    vmImage: 'windows-2019' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
#
#  steps:
#  - template:  templates/emulator-setup.yml
#
#  - task: DotNetCoreCLI@2
#    displayName: Test Microsoft.Azure.Cosmos.NetFramework.Tests
#    inputs:
#      command: test 
#      projects: 'Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.NetFramework.Tests/*.csproj'
#      arguments: ' --filter "TestCategory!=Quarantine" '
#      configuration: '$(BuildConfiguration)'
#      publishTestResults: true 
#
#
#- job: 
#  displayName: Microsoft.Azure.Cosmos.EmulatorTests
#  pool:
#    vmImage: 'windows-2019' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
#
#  steps:
#  - template:  templates/emulator-setup.yml
#
#  - task: DotNetCoreCLI@2
#    displayName: Test Microsoft.Azure.Cosmos.EmulatorTests
#    inputs:
#      command: test 
#      projects: 'Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/*.csproj'
#      arguments: ' --filter "TestCategory!=Quarantine" '
#      configuration: '$(BuildConfiguration)'
#      publishTestResults: true 

