pool:
  vmImage: 'windows-2019' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops

steps:
- task: DotNetCoreCLI@2
  displayName: Build Microsoft.Azure.Cosmos Src
  inputs:
    command: build
    projects: 'Microsoft.Azure.Cosmos/src/*.csproj'
    arguments: '--configuration $(buildConfiguration)' 

- task: DotNetCoreCLI@2
  displayName: Test Microsoft.Azure.Cosmos.Tests
  inputs:
    command: test 
    projects: 'Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --filter "FullyQualifiedName=Microsoft.Azure.Cosmos.ContractTests"'

