variables:
  ReleaseArguments: ' --filter "FullyQualifiedName=Microsoft.Azure.Cosmos.Client.Test.SessionTokenTests" --verbosity normal '
  VmImage: vs2017-win2016 # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  BuildConfiguration: Release


steps: 
- template:  templates/build-test.yml
  parameters:
    BuildConfiguration: $(BuildConfiguration)
    Arguments: $(ReleaseArguments) /p:IsNightly=true /p:GeneratePackageOnBuild=true 
    VmImage: $(VmImage)
    
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    configuration: '$(BuildConfiguration)' 
    publishVstsFeed: '4000bd49-81c3-47f2-94d8-d1392b95c228/04efb628-f46d-4b48-ac4d-5af5b1c75043' #azure-cosmos-dotnet
    