variables:
  ReleaseArguments: ' --filter "TestCategory!=Quarantine" --verbosity normal '
  VmImage: vs2017-win2016 # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  BuildConfiguration: Release


steps: 
#- template:  templates/build-test.yml
#  parameters:
#    BuildConfiguration: $(BuildConfiguration)
#    Arguments: $(ReleaseArguments)
#    VmImage: $(VmImage)

- task: DotNetCoreCLI@2
  displayName: restore
  inputs: 
    command: restore  
    configuration: $(BuildConfiguration)

    
- task: DotNetCoreCLI@2
  displayName: Microsoft.Azure.Cosmos
  inputs: 
    command: build  
    configuration: $(BuildConfiguration)
    projects: 'Microsoft.Azure.Cosmos/src/*.csproj' 
    arguments: --configuration $(BuildConfiguration) /p:IsNightly=true /p:GeneratePackageOnBuild=true 
    
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    configuration: '$(BuildConfiguration)' 
    publishVstsFeed: '4000bd49-81c3-47f2-94d8-d1392b95c228/04efb628-f46d-4b48-ac4d-5af5b1c75043' #azure-cosmos-dotnet
    