name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: morrisoncole/pr-lint-action
      with:
        title-regex: '(\[Internal\]|\[v4\] )?.{3}.+: (Add|Fix) .{3}.+'
        on-failed-regex-comment: "Please follow the required format. [Internal] Category: (Add|Fix) Description"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
